// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7l8yXp-LN7L13NMVajdWJ0HJSkd2lWGE',
    appId: '1:76413378916:android:e008bac6027a54b6599a71',
    messagingSenderId: '76413378916',
    projectId: 'my-project-ae9db',
    storageBucket: 'my-project-ae9db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJqgBSSdVNQlfF8f04Nd0cig-B0K-Ulmg',
    appId: '1:76413378916:ios:aadd4a386168317c599a71',
    messagingSenderId: '76413378916',
    projectId: 'my-project-ae9db',
    storageBucket: 'my-project-ae9db.appspot.com',
    iosBundleId: 'com.example.sabak34FirebaseTodo1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3c8vh_tMa-yQYRbk8JtnyV5BGodimWcc',
    appId: '1:76413378916:web:319a663b3e36e599599a71',
    messagingSenderId: '76413378916',
    projectId: 'my-project-ae9db',
    authDomain: 'my-project-ae9db.firebaseapp.com',
    storageBucket: 'my-project-ae9db.appspot.com',
  );
}
